/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TargetReference contains enough information to let you identify an workload for PodUnavailableBudget Selector and TargetReference are mutually exclusive, TargetReference is priority to take effect
 */
@ApiModel(description = "TargetReference contains enough information to let you identify an workload for PodUnavailableBudget Selector and TargetReference are mutually exclusive, TargetReference is priority to take effect")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruisePolicyV1alpha1PodUnavailableBudgetSpecTargetRef {
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("name")
  private String name = null;

  public KruisePolicyV1alpha1PodUnavailableBudgetSpecTargetRef apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * API version of the referent.
   * @return apiVersion
  **/
  @ApiModelProperty(value = "API version of the referent.")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public KruisePolicyV1alpha1PodUnavailableBudgetSpecTargetRef kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Kind of the referent.
   * @return kind
  **/
  @ApiModelProperty(value = "Kind of the referent.")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public KruisePolicyV1alpha1PodUnavailableBudgetSpecTargetRef name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the referent.
   * @return name
  **/
  @ApiModelProperty(value = "Name of the referent.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruisePolicyV1alpha1PodUnavailableBudgetSpecTargetRef ioKruisePolicyV1alpha1PodUnavailableBudgetSpecTargetRef = (KruisePolicyV1alpha1PodUnavailableBudgetSpecTargetRef) o;
    return Objects.equals(this.apiVersion, ioKruisePolicyV1alpha1PodUnavailableBudgetSpecTargetRef.apiVersion) &&
        Objects.equals(this.kind, ioKruisePolicyV1alpha1PodUnavailableBudgetSpecTargetRef.kind) &&
        Objects.equals(this.name, ioKruisePolicyV1alpha1PodUnavailableBudgetSpecTargetRef.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruisePolicyV1alpha1PodUnavailableBudgetSpecTargetRef {\n");
    
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

