/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.client.models.KruiseAppsV1alpha1CloneSetSpecLifecycleInPlaceUpdate;
import io.openkruise.client.models.KruiseAppsV1alpha1CloneSetSpecLifecyclePreDelete;
import io.openkruise.client.models.KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Lifecycle defines the lifecycle hooks for Pods pre-available(pre-normal), pre-delete, in-place update.
 */
@ApiModel(description = "Lifecycle defines the lifecycle hooks for Pods pre-available(pre-normal), pre-delete, in-place update.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1CloneSetSpecLifecycle {
  @SerializedName("inPlaceUpdate")
  private KruiseAppsV1alpha1CloneSetSpecLifecycleInPlaceUpdate inPlaceUpdate = null;

  @SerializedName("preDelete")
  private KruiseAppsV1alpha1CloneSetSpecLifecyclePreDelete preDelete = null;

  @SerializedName("preNormal")
  private KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal preNormal = null;

  public KruiseAppsV1alpha1CloneSetSpecLifecycle inPlaceUpdate(KruiseAppsV1alpha1CloneSetSpecLifecycleInPlaceUpdate inPlaceUpdate) {
    this.inPlaceUpdate = inPlaceUpdate;
    return this;
  }

   /**
   * Get inPlaceUpdate
   * @return inPlaceUpdate
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1CloneSetSpecLifecycleInPlaceUpdate getInPlaceUpdate() {
    return inPlaceUpdate;
  }

  public void setInPlaceUpdate(KruiseAppsV1alpha1CloneSetSpecLifecycleInPlaceUpdate inPlaceUpdate) {
    this.inPlaceUpdate = inPlaceUpdate;
  }

  public KruiseAppsV1alpha1CloneSetSpecLifecycle preDelete(KruiseAppsV1alpha1CloneSetSpecLifecyclePreDelete preDelete) {
    this.preDelete = preDelete;
    return this;
  }

   /**
   * Get preDelete
   * @return preDelete
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1CloneSetSpecLifecyclePreDelete getPreDelete() {
    return preDelete;
  }

  public void setPreDelete(KruiseAppsV1alpha1CloneSetSpecLifecyclePreDelete preDelete) {
    this.preDelete = preDelete;
  }

  public KruiseAppsV1alpha1CloneSetSpecLifecycle preNormal(KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal preNormal) {
    this.preNormal = preNormal;
    return this;
  }

   /**
   * Get preNormal
   * @return preNormal
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal getPreNormal() {
    return preNormal;
  }

  public void setPreNormal(KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal preNormal) {
    this.preNormal = preNormal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1CloneSetSpecLifecycle ioKruiseAppsV1alpha1CloneSetSpecLifecycle = (KruiseAppsV1alpha1CloneSetSpecLifecycle) o;
    return Objects.equals(this.inPlaceUpdate, ioKruiseAppsV1alpha1CloneSetSpecLifecycle.inPlaceUpdate) &&
        Objects.equals(this.preDelete, ioKruiseAppsV1alpha1CloneSetSpecLifecycle.preDelete) &&
        Objects.equals(this.preNormal, ioKruiseAppsV1alpha1CloneSetSpecLifecycle.preNormal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inPlaceUpdate, preDelete, preNormal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1CloneSetSpecLifecycle {\n");
    
    sb.append("    inPlaceUpdate: ").append(toIndentedString(inPlaceUpdate)).append("\n");
    sb.append("    preDelete: ").append(toIndentedString(preDelete)).append("\n");
    sb.append("    preNormal: ").append(toIndentedString(preNormal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

