/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * PreNormal is the hook after Pod to be created and ready to be Normal.
 */
@ApiModel(description = "PreNormal is the hook after Pod to be created and ready to be Normal.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal {
  @SerializedName("finalizersHandler")
  private List<String> finalizersHandler = null;

  @SerializedName("labelsHandler")
  private Map<String, String> labelsHandler = null;

  @SerializedName("markPodNotReady")
  private Boolean markPodNotReady = null;

  public KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal finalizersHandler(List<String> finalizersHandler) {
    this.finalizersHandler = finalizersHandler;
    return this;
  }

  public KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal addFinalizersHandlerItem(String finalizersHandlerItem) {
    if (this.finalizersHandler == null) {
      this.finalizersHandler = new ArrayList<String>();
    }
    this.finalizersHandler.add(finalizersHandlerItem);
    return this;
  }

   /**
   * Get finalizersHandler
   * @return finalizersHandler
  **/
  @ApiModelProperty(value = "")
  public List<String> getFinalizersHandler() {
    return finalizersHandler;
  }

  public void setFinalizersHandler(List<String> finalizersHandler) {
    this.finalizersHandler = finalizersHandler;
  }

  public KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal labelsHandler(Map<String, String> labelsHandler) {
    this.labelsHandler = labelsHandler;
    return this;
  }

  public KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal putLabelsHandlerItem(String key, String labelsHandlerItem) {
    if (this.labelsHandler == null) {
      this.labelsHandler = new HashMap<String, String>();
    }
    this.labelsHandler.put(key, labelsHandlerItem);
    return this;
  }

   /**
   * Get labelsHandler
   * @return labelsHandler
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getLabelsHandler() {
    return labelsHandler;
  }

  public void setLabelsHandler(Map<String, String> labelsHandler) {
    this.labelsHandler = labelsHandler;
  }

  public KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal markPodNotReady(Boolean markPodNotReady) {
    this.markPodNotReady = markPodNotReady;
    return this;
  }

   /**
   * MarkPodNotReady &#x3D; true means: - Pod will be set to &#39;NotReady&#39; at preparingDelete/preparingUpdate state. - Pod will be restored to &#39;Ready&#39; at Updated state if it was set to &#39;NotReady&#39; at preparingUpdate state. Currently, MarkPodNotReady only takes effect on InPlaceUpdate &amp; PreDelete hook. Default to false.
   * @return markPodNotReady
  **/
  @ApiModelProperty(value = "MarkPodNotReady = true means: - Pod will be set to 'NotReady' at preparingDelete/preparingUpdate state. - Pod will be restored to 'Ready' at Updated state if it was set to 'NotReady' at preparingUpdate state. Currently, MarkPodNotReady only takes effect on InPlaceUpdate & PreDelete hook. Default to false.")
  public Boolean isMarkPodNotReady() {
    return markPodNotReady;
  }

  public void setMarkPodNotReady(Boolean markPodNotReady) {
    this.markPodNotReady = markPodNotReady;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal ioKruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal = (KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal) o;
    return Objects.equals(this.finalizersHandler, ioKruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal.finalizersHandler) &&
        Objects.equals(this.labelsHandler, ioKruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal.labelsHandler) &&
        Objects.equals(this.markPodNotReady, ioKruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal.markPodNotReady);
  }

  @Override
  public int hashCode() {
    return Objects.hash(finalizersHandler, labelsHandler, markPodNotReady);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1CloneSetSpecLifecyclePreNormal {\n");
    
    sb.append("    finalizersHandler: ").append(toIndentedString(finalizersHandler)).append("\n");
    sb.append("    labelsHandler: ").append(toIndentedString(labelsHandler)).append("\n");
    sb.append("    markPodNotReady: ").append(toIndentedString(markPodNotReady)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

