/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.client.models.KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyOrderPriority;
import io.openkruise.client.models.KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyWeightPriority;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Priorities are the rules for calculating the priority of updating pods. Each pod to be updated, will pass through these terms and get a sum of weights.
 */
@ApiModel(description = "Priorities are the rules for calculating the priority of updating pods. Each pod to be updated, will pass through these terms and get a sum of weights.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategy {
  @SerializedName("orderPriority")
  private List<KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyOrderPriority> orderPriority = null;

  @SerializedName("weightPriority")
  private List<KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyWeightPriority> weightPriority = null;

  public KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategy orderPriority(List<KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyOrderPriority> orderPriority) {
    this.orderPriority = orderPriority;
    return this;
  }

  public KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategy addOrderPriorityItem(KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyOrderPriority orderPriorityItem) {
    if (this.orderPriority == null) {
      this.orderPriority = new ArrayList<KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyOrderPriority>();
    }
    this.orderPriority.add(orderPriorityItem);
    return this;
  }

   /**
   * Order priority terms, pods will be sorted by the value of orderedKey. For example: &#x60;&#x60;&#x60; orderPriority: - orderedKey: key1 - orderedKey: key2 &#x60;&#x60;&#x60; First, all pods which have key1 in labels will be sorted by the value of key1. Then, the left pods which have no key1 but have key2 in labels will be sorted by the value of key2 and put behind those pods have key1.
   * @return orderPriority
  **/
  @ApiModelProperty(value = "Order priority terms, pods will be sorted by the value of orderedKey. For example: ``` orderPriority: - orderedKey: key1 - orderedKey: key2 ``` First, all pods which have key1 in labels will be sorted by the value of key1. Then, the left pods which have no key1 but have key2 in labels will be sorted by the value of key2 and put behind those pods have key1.")
  public List<KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyOrderPriority> getOrderPriority() {
    return orderPriority;
  }

  public void setOrderPriority(List<KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyOrderPriority> orderPriority) {
    this.orderPriority = orderPriority;
  }

  public KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategy weightPriority(List<KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyWeightPriority> weightPriority) {
    this.weightPriority = weightPriority;
    return this;
  }

  public KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategy addWeightPriorityItem(KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyWeightPriority weightPriorityItem) {
    if (this.weightPriority == null) {
      this.weightPriority = new ArrayList<KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyWeightPriority>();
    }
    this.weightPriority.add(weightPriorityItem);
    return this;
  }

   /**
   * Weight priority terms, pods will be sorted by the sum of all terms weight.
   * @return weightPriority
  **/
  @ApiModelProperty(value = "Weight priority terms, pods will be sorted by the sum of all terms weight.")
  public List<KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyWeightPriority> getWeightPriority() {
    return weightPriority;
  }

  public void setWeightPriority(List<KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategyWeightPriority> weightPriority) {
    this.weightPriority = weightPriority;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategy ioKruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategy = (KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategy) o;
    return Objects.equals(this.orderPriority, ioKruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategy.orderPriority) &&
        Objects.equals(this.weightPriority, ioKruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategy.weightPriority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderPriority, weightPriority);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1CloneSetSpecUpdateStrategyPriorityStrategy {\n");
    
    sb.append("    orderPriority: ").append(toIndentedString(orderPriority)).append("\n");
    sb.append("    weightPriority: ").append(toIndentedString(weightPriority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

