/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TargetReference is the target workload that WorkloadSpread want to control.
 */
@ApiModel(description = "TargetReference is the target workload that WorkloadSpread want to control.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1WorkloadSpreadSpecTargetRef {
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("name")
  private String name = null;

  public KruiseAppsV1alpha1WorkloadSpreadSpecTargetRef apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * API version of the referent.
   * @return apiVersion
  **/
  @ApiModelProperty(required = true, value = "API version of the referent.")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public KruiseAppsV1alpha1WorkloadSpreadSpecTargetRef kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Kind of the referent.
   * @return kind
  **/
  @ApiModelProperty(required = true, value = "Kind of the referent.")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public KruiseAppsV1alpha1WorkloadSpreadSpecTargetRef name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the referent.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the referent.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1WorkloadSpreadSpecTargetRef ioKruiseAppsV1alpha1WorkloadSpreadSpecTargetRef = (KruiseAppsV1alpha1WorkloadSpreadSpecTargetRef) o;
    return Objects.equals(this.apiVersion, ioKruiseAppsV1alpha1WorkloadSpreadSpecTargetRef.apiVersion) &&
        Objects.equals(this.kind, ioKruiseAppsV1alpha1WorkloadSpreadSpecTargetRef.kind) &&
        Objects.equals(this.name, ioKruiseAppsV1alpha1WorkloadSpreadSpecTargetRef.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1WorkloadSpreadSpecTargetRef {\n");
    
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

