/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.client.models.KruiseAppsV1alpha1WorkloadSpreadSpecPreference;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * An empty preferred scheduling term matches all objects with implicit weight 0 (i.e. it&#39;s a no-op). A null preferred scheduling term matches no objects (i.e. is also a no-op).
 */
@ApiModel(description = "An empty preferred scheduling term matches all objects with implicit weight 0 (i.e. it's a no-op). A null preferred scheduling term matches no objects (i.e. is also a no-op).")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1WorkloadSpreadSpecPreferredNodeSelectorTerms {
  @SerializedName("preference")
  private KruiseAppsV1alpha1WorkloadSpreadSpecPreference preference = null;

  @SerializedName("weight")
  private Integer weight = null;

  public KruiseAppsV1alpha1WorkloadSpreadSpecPreferredNodeSelectorTerms preference(KruiseAppsV1alpha1WorkloadSpreadSpecPreference preference) {
    this.preference = preference;
    return this;
  }

   /**
   * Get preference
   * @return preference
  **/
  @ApiModelProperty(required = true, value = "")
  public KruiseAppsV1alpha1WorkloadSpreadSpecPreference getPreference() {
    return preference;
  }

  public void setPreference(KruiseAppsV1alpha1WorkloadSpreadSpecPreference preference) {
    this.preference = preference;
  }

  public KruiseAppsV1alpha1WorkloadSpreadSpecPreferredNodeSelectorTerms weight(Integer weight) {
    this.weight = weight;
    return this;
  }

   /**
   * Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
   * @return weight
  **/
  @ApiModelProperty(required = true, value = "Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.")
  public Integer getWeight() {
    return weight;
  }

  public void setWeight(Integer weight) {
    this.weight = weight;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1WorkloadSpreadSpecPreferredNodeSelectorTerms ioKruiseAppsV1alpha1WorkloadSpreadSpecPreferredNodeSelectorTerms = (KruiseAppsV1alpha1WorkloadSpreadSpecPreferredNodeSelectorTerms) o;
    return Objects.equals(this.preference, ioKruiseAppsV1alpha1WorkloadSpreadSpecPreferredNodeSelectorTerms.preference) &&
        Objects.equals(this.weight, ioKruiseAppsV1alpha1WorkloadSpreadSpecPreferredNodeSelectorTerms.weight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preference, weight);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1WorkloadSpreadSpecPreferredNodeSelectorTerms {\n");
    
    sb.append("    preference: ").append(toIndentedString(preference)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

