/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.openapi.models.V1ObjectMeta;
import io.openkruise.client.models.KruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplateSpec;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Specifies the broadcastjob that will be created when executing a BroadcastCronJob.
 */
@ApiModel(description = "Specifies the broadcastjob that will be created when executing a BroadcastCronJob.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplate {
  @SerializedName("metadata")
  private V1ObjectMeta metadata = null;

  @SerializedName("spec")
  private KruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplateSpec spec = null;

  public KruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplate metadata(V1ObjectMeta metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Standard object&#39;s metadata of the jobs created from this template.
   * @return metadata
  **/
  @ApiModelProperty(value = "Standard object's metadata of the jobs created from this template.")
  public V1ObjectMeta getMetadata() {
    return metadata;
  }

  public void setMetadata(V1ObjectMeta metadata) {
    this.metadata = metadata;
  }

  public KruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplate spec(KruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplateSpec spec) {
    this.spec = spec;
    return this;
  }

   /**
   * Get spec
   * @return spec
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplateSpec getSpec() {
    return spec;
  }

  public void setSpec(KruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplateSpec spec) {
    this.spec = spec;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplate ioKruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplate = (KruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplate) o;
    return Objects.equals(this.metadata, ioKruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplate.metadata) &&
        Objects.equals(this.spec, ioKruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplate.spec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, spec);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1AdvancedCronJobSpecTemplateBroadcastJobTemplate {\n");
    
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

