/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.client.models.KruiseAppsV1alpha1NodePodProbeSpecPodProbes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * NodePodProbeSpec defines the desired state of NodePodProbe
 */
@ApiModel(description = "NodePodProbeSpec defines the desired state of NodePodProbe")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1NodePodProbeSpec {
  @SerializedName("podProbes")
  private List<KruiseAppsV1alpha1NodePodProbeSpecPodProbes> podProbes = null;

  public KruiseAppsV1alpha1NodePodProbeSpec podProbes(List<KruiseAppsV1alpha1NodePodProbeSpecPodProbes> podProbes) {
    this.podProbes = podProbes;
    return this;
  }

  public KruiseAppsV1alpha1NodePodProbeSpec addPodProbesItem(KruiseAppsV1alpha1NodePodProbeSpecPodProbes podProbesItem) {
    if (this.podProbes == null) {
      this.podProbes = new ArrayList<KruiseAppsV1alpha1NodePodProbeSpecPodProbes>();
    }
    this.podProbes.add(podProbesItem);
    return this;
  }

   /**
   * Get podProbes
   * @return podProbes
  **/
  @ApiModelProperty(value = "")
  public List<KruiseAppsV1alpha1NodePodProbeSpecPodProbes> getPodProbes() {
    return podProbes;
  }

  public void setPodProbes(List<KruiseAppsV1alpha1NodePodProbeSpecPodProbes> podProbes) {
    this.podProbes = podProbes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1NodePodProbeSpec ioKruiseAppsV1alpha1NodePodProbeSpec = (KruiseAppsV1alpha1NodePodProbeSpec) o;
    return Objects.equals(this.podProbes, ioKruiseAppsV1alpha1NodePodProbeSpec.podProbes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(podProbes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1NodePodProbeSpec {\n");
    
    sb.append("    podProbes: ").append(toIndentedString(podProbes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

