/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.client.models.KruiseAppsV1alpha1StatefulSetSpecUpdateStrategyRollingUpdate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * updateStrategy indicates the StatefulSetUpdateStrategy that will be employed to update Pods in the StatefulSet when a revision is made to Template.
 */
@ApiModel(description = "updateStrategy indicates the StatefulSetUpdateStrategy that will be employed to update Pods in the StatefulSet when a revision is made to Template.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1StatefulSetSpecUpdateStrategy {
  @SerializedName("rollingUpdate")
  private KruiseAppsV1alpha1StatefulSetSpecUpdateStrategyRollingUpdate rollingUpdate = null;

  @SerializedName("type")
  private String type = null;

  public KruiseAppsV1alpha1StatefulSetSpecUpdateStrategy rollingUpdate(KruiseAppsV1alpha1StatefulSetSpecUpdateStrategyRollingUpdate rollingUpdate) {
    this.rollingUpdate = rollingUpdate;
    return this;
  }

   /**
   * Get rollingUpdate
   * @return rollingUpdate
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1StatefulSetSpecUpdateStrategyRollingUpdate getRollingUpdate() {
    return rollingUpdate;
  }

  public void setRollingUpdate(KruiseAppsV1alpha1StatefulSetSpecUpdateStrategyRollingUpdate rollingUpdate) {
    this.rollingUpdate = rollingUpdate;
  }

  public KruiseAppsV1alpha1StatefulSetSpecUpdateStrategy type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type indicates the type of the StatefulSetUpdateStrategy. Default is RollingUpdate.
   * @return type
  **/
  @ApiModelProperty(value = "Type indicates the type of the StatefulSetUpdateStrategy. Default is RollingUpdate.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1StatefulSetSpecUpdateStrategy ioKruiseAppsV1alpha1StatefulSetSpecUpdateStrategy = (KruiseAppsV1alpha1StatefulSetSpecUpdateStrategy) o;
    return Objects.equals(this.rollingUpdate, ioKruiseAppsV1alpha1StatefulSetSpecUpdateStrategy.rollingUpdate) &&
        Objects.equals(this.type, ioKruiseAppsV1alpha1StatefulSetSpecUpdateStrategy.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rollingUpdate, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1StatefulSetSpecUpdateStrategy {\n");
    
    sb.append("    rollingUpdate: ").append(toIndentedString(rollingUpdate)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

