/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * KruiseAppsV1alpha1PersistentPodStateSpecPreference
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1PersistentPodStateSpecPreference {
  @SerializedName("nodeTopologyKeys")
  private List<String> nodeTopologyKeys = new ArrayList<String>();

  public KruiseAppsV1alpha1PersistentPodStateSpecPreference nodeTopologyKeys(List<String> nodeTopologyKeys) {
    this.nodeTopologyKeys = nodeTopologyKeys;
    return this;
  }

  public KruiseAppsV1alpha1PersistentPodStateSpecPreference addNodeTopologyKeysItem(String nodeTopologyKeysItem) {
    this.nodeTopologyKeys.add(nodeTopologyKeysItem);
    return this;
  }

   /**
   * A list of node selector requirements by node&#39;s labels.
   * @return nodeTopologyKeys
  **/
  @ApiModelProperty(required = true, value = "A list of node selector requirements by node's labels.")
  public List<String> getNodeTopologyKeys() {
    return nodeTopologyKeys;
  }

  public void setNodeTopologyKeys(List<String> nodeTopologyKeys) {
    this.nodeTopologyKeys = nodeTopologyKeys;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1PersistentPodStateSpecPreference ioKruiseAppsV1alpha1PersistentPodStateSpecPreference = (KruiseAppsV1alpha1PersistentPodStateSpecPreference) o;
    return Objects.equals(this.nodeTopologyKeys, ioKruiseAppsV1alpha1PersistentPodStateSpecPreference.nodeTopologyKeys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nodeTopologyKeys);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1PersistentPodStateSpecPreference {\n");
    
    sb.append("    nodeTopologyKeys: ").append(toIndentedString(nodeTopologyKeys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

