/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.client.models.KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Indicates the node selector to form the subset. Depending on the node selector, pods provisioned could be distributed across multiple groups of nodes. A subset&#39;s nodeSelectorTerm is not allowed to be updated.
 */
@ApiModel(description = "Indicates the node selector to form the subset. Depending on the node selector, pods provisioned could be distributed across multiple groups of nodes. A subset's nodeSelectorTerm is not allowed to be updated.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTerm {
  @SerializedName("matchExpressions")
  private List<KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions> matchExpressions = null;

  @SerializedName("matchFields")
  private List<KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions> matchFields = null;

  public KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTerm matchExpressions(List<KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions> matchExpressions) {
    this.matchExpressions = matchExpressions;
    return this;
  }

  public KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTerm addMatchExpressionsItem(KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions matchExpressionsItem) {
    if (this.matchExpressions == null) {
      this.matchExpressions = new ArrayList<KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions>();
    }
    this.matchExpressions.add(matchExpressionsItem);
    return this;
  }

   /**
   * A list of node selector requirements by node&#39;s labels.
   * @return matchExpressions
  **/
  @ApiModelProperty(value = "A list of node selector requirements by node's labels.")
  public List<KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions> getMatchExpressions() {
    return matchExpressions;
  }

  public void setMatchExpressions(List<KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions> matchExpressions) {
    this.matchExpressions = matchExpressions;
  }

  public KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTerm matchFields(List<KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions> matchFields) {
    this.matchFields = matchFields;
    return this;
  }

  public KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTerm addMatchFieldsItem(KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions matchFieldsItem) {
    if (this.matchFields == null) {
      this.matchFields = new ArrayList<KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions>();
    }
    this.matchFields.add(matchFieldsItem);
    return this;
  }

   /**
   * A list of node selector requirements by node&#39;s fields.
   * @return matchFields
  **/
  @ApiModelProperty(value = "A list of node selector requirements by node's fields.")
  public List<KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions> getMatchFields() {
    return matchFields;
  }

  public void setMatchFields(List<KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTermMatchExpressions> matchFields) {
    this.matchFields = matchFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTerm ioKruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTerm = (KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTerm) o;
    return Objects.equals(this.matchExpressions, ioKruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTerm.matchExpressions) &&
        Objects.equals(this.matchFields, ioKruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTerm.matchFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchExpressions, matchFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1UnitedDeploymentSpecTopologyNodeSelectorTerm {\n");
    
    sb.append("    matchExpressions: ").append(toIndentedString(matchExpressions)).append("\n");
    sb.append("    matchFields: ").append(toIndentedString(matchFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

