/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.client.models.KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopExec;
import io.openkruise.client.models.KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopHttpGet;
import io.openkruise.client.models.KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopTcpSocket;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PreStop is synced from the real container in Pod spec during this ContainerRecreateRequest creating. Populated by the system. Read-only.
 */
@ApiModel(description = "PreStop is synced from the real container in Pod spec during this ContainerRecreateRequest creating. Populated by the system. Read-only.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStop {
  @SerializedName("exec")
  private KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopExec exec = null;

  @SerializedName("httpGet")
  private KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopHttpGet httpGet = null;

  @SerializedName("tcpSocket")
  private KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopTcpSocket tcpSocket = null;

  public KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStop exec(KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopExec exec) {
    this.exec = exec;
    return this;
  }

   /**
   * Get exec
   * @return exec
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopExec getExec() {
    return exec;
  }

  public void setExec(KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopExec exec) {
    this.exec = exec;
  }

  public KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStop httpGet(KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopHttpGet httpGet) {
    this.httpGet = httpGet;
    return this;
  }

   /**
   * Get httpGet
   * @return httpGet
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopHttpGet getHttpGet() {
    return httpGet;
  }

  public void setHttpGet(KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopHttpGet httpGet) {
    this.httpGet = httpGet;
  }

  public KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStop tcpSocket(KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopTcpSocket tcpSocket) {
    this.tcpSocket = tcpSocket;
    return this;
  }

   /**
   * Get tcpSocket
   * @return tcpSocket
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopTcpSocket getTcpSocket() {
    return tcpSocket;
  }

  public void setTcpSocket(KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStopTcpSocket tcpSocket) {
    this.tcpSocket = tcpSocket;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStop ioKruiseAppsV1alpha1ContainerRecreateRequestSpecPreStop = (KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStop) o;
    return Objects.equals(this.exec, ioKruiseAppsV1alpha1ContainerRecreateRequestSpecPreStop.exec) &&
        Objects.equals(this.httpGet, ioKruiseAppsV1alpha1ContainerRecreateRequestSpecPreStop.httpGet) &&
        Objects.equals(this.tcpSocket, ioKruiseAppsV1alpha1ContainerRecreateRequestSpecPreStop.tcpSocket);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exec, httpGet, tcpSocket);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1ContainerRecreateRequestSpecPreStop {\n");
    
    sb.append("    exec: ").append(toIndentedString(exec)).append("\n");
    sb.append("    httpGet: ").append(toIndentedString(httpGet)).append("\n");
    sb.append("    tcpSocket: ").append(toIndentedString(tcpSocket)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

